### ISSUE TITLE
'nick-mandziak.vscode-cucumber-js-runner' CANNOT use API proposal: testCoverage.

### ISSUE THREAD

**Issue by DavidYZL** [mandziak-nv/vscode-cucumber-js-runner#3]
### Problem:

I try to run my cucumber tests, there is no output in test results, and display an error dialog of VS Code:

`
An error occurred attempting to run tests: Error: Extension 'nick-mandziak.vscode-cucumber-js-runner' CANNOT use API proposal: testCoverage. Its package.json#enabledApiProposals-property declares: [] but NOT testCoverage. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api nick-mandziak.vscode-cucumber-js-runner
`

### My VS Code version:
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

### My remote server version:
Linux version 5.4.119-19.0009.28
Debian GNU/Linux 12

**Comment by mandziak-nv** [comment]
Should be fixed after v1.89
