### ISSUE TITLE
Allow `cucumberPath` to be configurable via `settings.json`

### ISSUE THREAD

**Issue by travis-tesouro** [mandziak-nv/vscode-cucumber-js-runner#4]
To support repos where `node_modules` does not sit at the root of the VS Code workspace, allow the `cucumberPath` to be configurable via `settings.json`.

https://github.com/mandziak-nv/vscode-cucumber-js-runner/blob/70c944ba7db691c5522c183e45fdd34cd3ccfd23/src/cucumber/CucumberRunner.ts#L33

Thank you!

**Comment by mandziak-nv** [comment]
Done. Starting with v1.89.2, you can use `cucumber_path` configuration option to specify the path to the cucumber command.
